version: '3'
services:

  user-mysql:
     image: mysql:5.7     
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_PASSWORD: root
       MYSQL_DATABASE: demo1DB
       MYSQL_HOST: localhost
  user-mongo:
     image: mongo
     ports:
       - "27017:27017"
     environment:
       MONGO_DATABASE: demo2DB
       MONGO_PORT: 27017
       MONGO_HOST: localhost

  userauthimage:
    image: user-auth
    build:
      context: UserAuthentication-Service/
    restart: always
    ports:
      - 8089:8089
    depends_on:
      - user-mysql
      
  noteserviceimage:
    image: note-app
    build:
      context: NoteService/
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - user-mongo
      
      
  userserviceimage:
     image: user-app
     build:
       context: UserService/
     restart: always
     ports:
       - 8081:8081
     depends_on:
       - user-mongo