spring:
  data:
    mongodb:
#      authentication-database: dbAdmin
     
      database: keepnote6user
      port: 27017
      host: localhost
  application:
    name: user-service
server:
  port: 8081



